---
version: 2
plan:
  project-key: PROJ
  key: nmk
  name: nmk
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  tasks:
  - checkout:
      force-clean-build: 'false'
  - script:
      interpreter: SHELL
      scripts:
      - docker build . --no-cache -t bamboo-agent -f Dockerfile
  - any-task:
      plugin-key: aqua-scanner.aqua-scanner:aqua-scanner
      configuration:
        globalApiUrl: http://18.191.149.177:8080
        globalAquaPassword: '@Password1'
        imageName: bamboo-agent:latest
        globalScannerImage: registry.aquasec.com/scanner:5.3
        locationType: local
        aquaConfig: current
        globalAquaUser: administrator
        globalAdditionalDockerOptions: -e SCALOCK_LOG_LEVEL=DEBUG
        useContextVariable: 'false'
        globalCaCertificates: 'true'
        register: 'true'
triggers:
- polling:
    period: '180'
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: PROJ-nmk
plan-permissions:
- users:
  - bamboo
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
...
